-- =====================================================
-- MedScope Pharmacy Analytics
-- 01_load_raw_data.sql
-- Purpose: Load staged raw CSV files into Snowflake RAW tables.
--
-- First run 01_create_tables.sql, then upload the six files from data/raw/
-- to @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE using Snowsight or SnowSQL.
-- =====================================================

-- Confirm that the expected files are present before loading.
LIST @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE;

COPY INTO MEDSCOPE_DB.RAW.PATIENTS
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/patients_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MEDSCOPE_DB.RAW.DOCTORS
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/doctors_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MEDSCOPE_DB.RAW.PHARMACIES
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/pharmacies_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MEDSCOPE_DB.RAW.DRUGS
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/drugs_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MEDSCOPE_DB.RAW.PRESCRIPTIONS
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/prescriptions_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO MEDSCOPE_DB.RAW.INSURANCE_CLAIMS
FROM @MEDSCOPE_DB.RAW.MEDSCOPE_CSV_STAGE/insurance_claims_raw.csv
FILE_FORMAT = (FORMAT_NAME = 'MEDSCOPE_DB.RAW.MEDSCOPE_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';
